### ISSUE TITLE
As of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default

### ISSUE THREAD

**Issue by gemmakbarlow** [bitrise-io/steps-cocoapods-install#29] opened 2017-02-15 19:52 UTC
We've recently upgraded to CocoaPods 1.2.0, and are now seeing the following when using the CocoaPods Bitrise step:

```
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `Smooch (= 5.5.0)` required by `Podfile`
- `Smooch (= 5.5.0)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependency: `Smooch (= 5.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:57:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:719:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:717:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
[33;1mCommand failed, error: exit status 1, retrying without --no-repo-update ...[0m
[32;1m$ pod "_1.2.0_" "repo" "update"[0m
Updating spec repo `master`
  $ /usr/local/bin/git -C /Users/vagrant/.cocoapods/repos/master fetch origin
  From https://github.com/CocoaPods/Specs
     5d56631126e..19d4c6a04d4  master     -> origin/master
  $ /usr/local/bin/git -C /Users/vagrant/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/vagrant/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 19d4c6a04d4 [Add] NATableView 5.0.4
[32;1m$ pod "_1.2.0_" "install" "--verbose"[0m
  Preparing
```

I would imagine that this is related to the line
```
as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default
```
and something needing to be updated in the step itself.

**Comment by viktorbenei** [comment] 2017-02-16 11:42
Hi,

It seems to be a duplicate of this issue: https://discuss.bitrise.io/t/cocoapods-unable-to-satisfy-the-following-requirements/394

If you'd have any questions feel free to comment there!

Happy Building! :)

**Closed by viktorbenei** 2017-02-16 11:42 UTC

**Comment by gemmakbarlow** [comment] 2017-02-16 20:18
Not *quite* a duplicate, as there's no update to be made to the Podfile.lock mentioned in the solution above. 

Looking more carefully, I see it succeeds after re-attempting the `pod install` with different params; is this working as designed ? Is there an additional step I should be adding / different configuration I could be using to speed up the build? 

```
System installed cocoapods version:
[32;1m$ pod "--version"[0m
1.1.1

[34;1mSearching for Podfile[0m
[32;1mFound Podfile: /Users/vagrant/git/Harry's/Podfile[0m

[34;1mDetermining required cocoapods version[0m
Searching for Podfile.lock
Found Podfile.lock: /Users/vagrant/git/Harry's/Podfile.lock
[32;1mRequired CocoaPods version (from Podfile.lock): 1.2.0[0m

[34;1mInstall cocoapods version[0m
Checking cocoapods 1.2.0 gem
Installing
[32;1m$ gem "install" "cocoapods" "--no-document" "-v" "1.2.0"[0m

[34;1mInstalling Pods[0m
[32;1m$ pod "_1.2.0_" "install" "--no-repo-update" "--verbose"[0m
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Harrys`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Harrys Unit Tests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Harrys Networking Tests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Harrys Acceptance Tests`: (``)

Finding Podfile changes
  - 1PasswordExtension
  - AFNetworking
  - AFOAuth2Manager
  - AHKNavigationController
  - Branch
  - Crashlytics
  - FBSDKCoreKit
  - FBSDKLoginKit
  - FBSnapshotTestCase
  - FSCalendar
  - FXForms
  - Fabric
  - GBDeviceInfo
  - GBVersionTracking
  - GoogleTagManager
  - Heap
  - HockeySDK
  - JVFloatLabeledTextField
  - KIF
  - KMPlaceholderTextView
  - Locksmith
  - PureLayout
  - Router
  - Smooch
  - SmoochHelpKit
  - Stripe
  - SwiftTryCatch
  - SwiftyJSON
  - TTTAttributedLabel
  - iCarousel

Fetching external sources
-> Pre-downloading: `FXForms` from `git@github.com:harrystech/FXForms.git`, commit `48dc3781fd5979ed160226d72f4e3f174404d00f`
 > Git download
 > Git download
     $ /usr/local/bin/git clone git@github.com:harrystech/FXForms.git /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-1bfj1ig --template=
     Cloning into '/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-1bfj1ig'...
     Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
     
   $ /usr/local/bin/git -C /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-1bfj1ig checkout --quiet 48dc3781fd5979ed160226d72f4e3f174404d00f
  > Copying FXForms from `/Users/vagrant/Library/Caches/CocoaPods/Pods/External/FXForms/b1df6e248b5d67e96563bf625b2a958f` to `Pods/FXForms`
-> Pre-downloading: `KIF` from `git@github.com:harrystech/KIF.git`, commit `8684992f0774276da2f061a98e1f84b8aa9dfb96`
 > Git download
 > Git download
     $ /usr/local/bin/git clone git@github.com:harrystech/KIF.git /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-up9j0 --template=
     Cloning into '/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-up9j0'...
     Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
     
   $ /usr/local/bin/git -C /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-up9j0 checkout --quiet 8684992f0774276da2f061a98e1f84b8aa9dfb96
  > Copying KIF from `/Users/vagrant/Library/Caches/CocoaPods/Pods/External/KIF/42c5c84adb98f4ec80d3aea494ae8468` to `Pods/KIF`
-> Pre-downloading: `Router` from `https://github.com/ViacomInc/Router.git`, commit `833c7cc52b8b78cefe7e49069495f72d6e7dfb2a`
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/ViacomInc/Router.git /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-n9fazp --template=
     Cloning into '/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-n9fazp'...
   $ /usr/local/bin/git -C /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/d20170216-1502-n9fazp checkout --quiet 833c7cc52b8b78cefe7e49069495f72d6e7dfb2a
  > Copying Router from `/Users/vagrant/Library/Caches/CocoaPods/Pods/External/Router/bd5edf1fa1eba166a93d3768ac4cd112` to `Pods/Router`

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `Smooch (= 5.5.0)` required by `Podfile`
- `Smooch (= 5.5.0)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependency: `Smooch (= 5.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:57:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:719:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:717:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
[33;1mCommand failed, error: exit status 1, retrying without --no-repo-update ...[0m
```

**Comment by viktorbenei** [comment] 2017-02-16 20:20
If the retry works that's usually due to CocoaPods spec changes - the step does a CocoaPods spec update before the retry.

We update the cocoapods specs on the virtual machine every weekend ( https://discuss.bitrise.io/t/how-are-the-bitrise-io-stacks-updated-and-with-what-frequency/281 ) so the next update will most likely solve this, and no more retry (cocoapods spec repo update) will be required.

**Comment by gemmakbarlow** [comment] 2017-02-16 20:55
Sounds good, thanks. I'll keep my eye out for it.
